name: Build Terraform Deployment Image

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    tags:
      - "v*"

env:
  REPO: "sealio"
  BUILD_PLATFORMS: "linux/amd64,linux/arm64"

jobs:
  build-and-push:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
        with:
          image: tonistiigi/binfmt:qemu-v7.0.0
          platforms: "arm64"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Get Docker Metadata
        if: ${{ github.event_name != 'pull_request' }}
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REPO }}/terraform-deployer

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.CI_DOCKERHUB_USERNAME }}
          password: ${{ secrets.CI_DOCKERHUB_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          push: ${{ github.event_name != 'pull_request' }}
          context: .
          tags: ${{ steps.metadata.outputs.tags }}
          platforms: ${{ env.BUILD_PLATFORMS }}
          cache-from: |
            type=registry,ref=${{ env.REPO }}/build-cache:terraform-deployer${{ startsWith(github.ref, 'refs/tags/') && '-release' || '' }}
          cache-to: |
            ${{ github.event_name != 'pull_request' && format('type=registry,mode=max,oci-mediatypes=false,compression=gzip,ref={0}/build-cache:terraform-deployer{1},ignore-error=true', env.REPO, startsWith(github.ref, 'refs/tags/') && '-release' || '') || '' }}
          no-cache-filters: |
            ${{ startsWith(github.ref, 'refs/tags/') && 'fetch' || '' }}
